<?php echo $this->getButtonHtml() ?>
<span style="display: inline-block; position: relative; top: 3px; left: 10px;"><img id="googleverificationstatus" src="<?php echo $this->getCurrentStatusImage() ?>"></span>

<script>
    document.observe("dom:loaded", function() {
        Event.observe("verification_button", "click", function() {

            var confirmTextEnable = "Ich stimme zu, dass Google easymarketing bei meiner URL-Verifikation als weiteren \"Inhaber\" einträgt, damit easymarketing meine Daten für Google Shopping über die Schnittstelle pflegen und auslesen kann. Ich kann diese Zustimmung natürlich jederzeit widerrufen. easymarketing wird meine Daten unter keinen Umständen zu anderen Zwecken als meiner Kampagnen-Steuerung verwenden, weitergeben oder bei sich speichern.\n\nBei Durchführung der Verification wird der Magento Cache geleert.";
            var confirmTextDisable = "Bei Aufhebung der Verifikation wird der Magento Cache geleert.";

            <?php if(!$this->getCurrentStatus()) { ?>
            var confirmText = confirmTextEnable;
            <?php } else { ?>
            var confirmText = confirmTextDisable;
            <?php } ?>

            if(confirm(confirmText)) {
                new Ajax.Request('<?php echo $this->getVerificationUrl() ?>', {
                    method: 'get',
                    onComplete: function(response) {
                        var responseObj = response.responseJSON;
                        if(responseObj.status == 0) {
                            alert("Falscher Access Token.");
                        } else if(responseObj.status == 1) {
                            alert(responseObj.errors.join('<br>'));
                        } else if(responseObj.status == 2) {
                            $('googleverificationstatus').setAttribute('src', '<?php echo $this->getSuccessImage() ?>');
                            alert('Google Verification erfolgreich.');
                            confirmText = confirmTextDisable;
                        } else if(responseObj.status == 3) {
                            $('googleverificationstatus').setAttribute('src', '<?php echo $this->getFailImage() ?>');
                            alert('Google Verification deaktiviert.')
                            confirmText = confirmTextEnable;
                        }
                    }
                });
            }
        });
    });
</script>